<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Acton\TestAction::class => App\Acton\TestActionFactory::class,
            App\Handler\UserHandler::class => App\Handler\UserHandlerFactory::class,
            App\Handler\User\DeleteUserHandler::class => App\Handler\User\DeleteUserHandlerFactory::class,
            App\Handler\User\UserCreateHandler::class => App\Handler\User\UserCreateHandlerFactory::class,
            App\Handler\User\UserDeleteHandler::class => App\Handler\User\UserDeleteHandlerFactory::class,
            App\Handler\User\UserEditHandler::class => App\Handler\User\UserEditHandlerFactory::class,
            App\Handler\User\UserListHandler::class => App\Handler\User\UserListHandlerFactory::class,
            App\Middleware\Test::class => App\Middleware\TestFactory::class,
            App\User\DeleteUserHandler::class => App\User\DeleteUserHandlerFactory::class,
        ],
    ],
];
